destinations = [
    {
        "name": "Goa",
        "type": "local",
        "cost_per_person": [9000, 16000],
        "group_type": ["solo", "friends", "family"],
        "visa_required": False,
        "purpose": ["Relaxation", "Adventure", "Luxury"],
        "ideal_months": ["November", "December", "January", "February"],
        "not_ideal_months": ["June", "July", "August", "September"],
        "month_reasons": {
            "November": "Pleasant weather, start of tourist season",
            "December": "Festivals and peak tourist season",
            "January": "Cool and comfortable, great for outdoor activities",
            "February": "Ideal weather for beach and parties",
            "June": "Heavy monsoon rains, beaches less accessible",
            "July": "Monsoon season, poor outdoor conditions",
            "August": "Continued monsoon rains, not ideal for tourists",
            "September": "Monsoon ends late, still wet and humid"
        },
        "places_to_visit": ["Baga Beach", "Fort Aguada", "Dudhsagar Falls", "Anjuna Market"]
    },
    {
        "name": "Manali",
        "type": "local",
        "cost_per_person": [7000, 13000],
        "group_type": ["solo", "family", "friends"],
        "visa_required": False,
        "purpose": ["Adventure", "Nature", "Relaxation"],
        "ideal_months": ["March", "April", "May", "September", "October"],
        "not_ideal_months": ["December", "January", "February"],
        "month_reasons": {
            "March": "Snow starts melting, good for trekking",
            "April": "Pleasant weather, ideal for sightseeing",
            "May": "Warm and great for adventure activities",
            "September": "Post monsoon, clear skies",
            "October": "Mild weather, perfect for nature walks",
            "December": "Heavy snowfall, some roads may be closed",
            "January": "Very cold and harsh winter conditions",
            "February": "Cold with occasional snowfall"
        },
        "places_to_visit": ["Solang Valley", "Rohtang Pass", "Hadimba Temple", "Mall Road"]
    },
    {
        "name": "Jaipur",
        "type": "local",
        "cost_per_person": [6000, 11000],
        "group_type": ["family", "solo"],
        "visa_required": False,
        "purpose": ["Culture", "Luxury", "Relaxation"],
        "ideal_months": ["October", "November", "December", "January", "February"],
        "not_ideal_months": ["June", "July", "August", "September"],
        "month_reasons": {
            "October": "Start of cool season, good for sightseeing",
            "November": "Pleasant weather, cultural festivals",
            "December": "Cool and comfortable, peak tourist time",
            "January": "Chilly but great for outdoor tours",
            "February": "Mild weather, ideal for visiting forts",
            "June": "Very hot, not comfortable for sightseeing",
            "July": "Monsoon rains begin, humid weather",
            "August": "Wet and humid, low tourist activity",
            "September": "End of monsoon, still humid"
        },
        "places_to_visit": ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"]
    },
    {
        "name": "Ladakh",
        "type": "local",
        "cost_per_person": [12000, 21000],
        "group_type": ["solo", "friends"],
        "visa_required": False,
        "purpose": ["Adventure", "Nature"],
        "ideal_months": ["May", "June", "July", "August", "September"],
        "not_ideal_months": ["December", "January", "February", "March", "April", "October", "November"],
        "month_reasons": {
            "May": "Snow melts, perfect for biking and trekking",
            "June": "Clear skies and warm days",
            "July": "Ideal for adventure and sightseeing",
            "August": "Pleasant weather, fewer tourists",
            "September": "Great for photography and nature",
            "December": "Extreme cold, roads mostly closed",
            "January": "Severe winter, very harsh conditions",
            "February": "Snowbound and inaccessible",
            "March": "Still cold with snow",
            "April": "Slow thaw, some areas inaccessible",
            "October": "Cold begins, short season ends",
            "November": "Start of winter, difficult travel"
        },
        "places_to_visit": ["Pangong Lake", "Nubra Valley", "Magnetic Hill", "Leh Palace"]
    },
    {
        "name": "Dubai",
        "type": "foreign",
        "cost_per_person": [40000, 60000],
        "group_type": ["family", "friends"],
        "visa_required": True,
        "purpose": ["Luxury", "Culture", "Relaxation"],
        "ideal_months": ["November", "December", "January", "February", "March"],
        "not_ideal_months": ["June", "July", "August", "September"],
        "month_reasons": {
            "November": "Pleasant weather, start of tourist season",
            "December": "Peak season with festivals",
            "January": "Cool and comfortable",
            "February": "Ideal for outdoor activities",
            "March": "Warm but pleasant",
            "June": "Extreme heat, not suitable for outdoor",
            "July": "Very hot and humid",
            "August": "Peak summer heat, avoid outdoor",
            "September": "Still very hot and humid"
        },
        "places_to_visit": ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari"]
    },
    {
        "name": "Thailand",
        "type": "foreign",
        "cost_per_person": [30000, 45000],
        "group_type": ["solo", "friends"],
        "visa_required": True,
        "purpose": ["Beach", "Adventure", "Relaxation"],
        "ideal_months": ["November", "December", "January", "February", "March"],
        "not_ideal_months": ["May", "June", "July", "August", "September", "October"],
        "month_reasons": {
            "November": "End of rainy season, great beach weather",
            "December": "Peak tourist season",
            "January": "Pleasant weather, ideal for travel",
            "February": "Warm and sunny",
            "March": "Hot but manageable",
            "May": "Start of rainy season",
            "June": "Heavy rains, high humidity",
            "July": "Monsoon season, less ideal for tourists",
            "August": "Rain and humidity continue",
            "September": "Rainy and humid",
            "October": "Rainy, flooding risk"
        },
        "places_to_visit": ["Phuket", "Bangkok Grand Palace", "Chiang Mai", "Phi Phi Islands"]
    },
    {
        "name": "Bali",
        "type": "foreign",
        "cost_per_person": [35000, 50000],
        "group_type": ["solo", "family", "friends"],
        "visa_required": False,
        "purpose": ["Beach", "Relaxation", "Luxury"],
        "ideal_months": ["April", "May", "June", "September"],
        "not_ideal_months": ["January", "February", "March", "October", "November", "December"],
        "month_reasons": {
            "April": "Start of dry season, great weather",
            "May": "Pleasant and sunny",
            "June": "Dry and comfortable",
            "September": "End of dry season, ideal for travel",
            "January": "Wet season with heavy rains",
            "February": "Rainy and humid",
            "March": "Wet season continues",
            "October": "Start of rainy season",
            "November": "Rain increases",
            "December": "Peak rainy season"
        },
        "places_to_visit": ["Ubud", "Tanah Lot Temple", "Tegallalang Rice Terrace", "Kuta Beach"]
    },
    {
        "name": "Sikkim",
        "type": "local",
        "cost_per_person": [8000, 14000],
        "group_type": ["solo", "family"],
        "visa_required": False,
        "purpose": ["Nature", "Culture", "Relaxation"],
        "ideal_months": ["March", "April", "May", "September", "October", "November"],
        "not_ideal_months": ["December", "January", "February"],
        "month_reasons": {
            "March": "Spring bloom, pleasant weather",
            "April": "Ideal for trekking and sightseeing",
            "May": "Warm and clear",
            "September": "Post monsoon, clear skies",
            "October": "Perfect for nature lovers",
            "November": "Cool and peaceful",
            "December": "Cold and foggy",
            "January": "Very cold, snow possible",
            "February": "Cold weather continues"
        },
        "places_to_visit": ["Tsomgo Lake", "Nathula Pass", "Gangtok", "Rumtek Monastery"]
    },
    {
        "name": "Andaman Islands",
        "type": "local",
        "cost_per_person": [10000, 18000],
        "group_type": ["family", "friends"],
        "visa_required": False,
        "purpose": ["Beach", "Relaxation", "Nature"],
        "ideal_months": ["October", "November", "December", "January", "February", "March"],
        "not_ideal_months": ["May", "June", "July", "August", "September"],
        "month_reasons": {
            "October": "End of monsoon, clear waters",
            "November": "Ideal for beach and water sports",
            "December": "Pleasant weather and festivals",
            "January": "Cool and comfortable",
            "February": "Great for snorkeling and diving",
            "March": "Warm and sunny",
            "May": "Start of monsoon, heavy rains",
            "June": "Monsoon season, rough seas",
            "July": "Heavy rainfall, not suitable for tourists",
            "August": "Monsoon continues, avoid water activities",
            "September": "Monsoon tapering off, still wet"
        },
        "places_to_visit": ["Radhanagar Beach", "Cellular Jail", "Havelock Island", "Neil Island"]
    },
    {
        "name": "Singapore",
        "type": "foreign",
        "cost_per_person": [50000, 70000],
        "group_type": ["family", "friends"],
        "visa_required": True,
        "purpose": ["Luxury", "Culture", "Relaxation"],
        "ideal_months": ["February", "March", "April", "May", "June"],
        "not_ideal_months": ["November", "December", "January"],
        "month_reasons": {
            "February": "Warm and less rainy",
            "March": "Pleasant weather, good for city tours",
            "April": "Warm and humid, but manageable",
            "May": "Good for sightseeing and events",
            "June": "Start of rainy season, short showers",
            "November": "Heavy rain and humidity",
            "December": "Frequent thunderstorms",
            "January": "Cool but wet weather"
        },
        "places_to_visit": ["Marina Bay Sands", "Gardens by the Bay", "Sentosa Island", "Orchard Road"]
    },
    {
        "name": "Rajasthan Desert Safari",
        "type": "local",
        "cost_per_person": [8000, 15000],
        "group_type": ["family", "friends"],
        "visa_required": False,
        "purpose": ["Culture", "Adventure", "Relaxation"],
        "ideal_months": ["October", "November", "December", "January", "February"],
        "not_ideal_months": ["May", "June", "July", "August", "September"],
        "month_reasons": {
            "October": "Cooler desert nights, pleasant tours",
            "November": "Cultural festivals and camel fairs",
            "December": "Peak tourist time with great weather",
            "January": "Cool climate, desert camps popular",
            "February": "Mild weather, good for sightseeing",
            "May": "Scorching hot, avoid daytime travel",
            "June": "Extreme heat",
            "July": "Humidity and monsoon showers",
            "August": "Humid, not ideal",
            "September": "Heat lingers, uncomfortable"
        },
        "places_to_visit": ["Jaisalmer Fort", "Sam Sand Dunes", "Camel Safari", "Desert Camp"]
    },
    {
        "name": "Varanasi",
        "type": "local",
        "cost_per_person": [6000, 12000],
        "group_type": ["solo", "family"],
        "visa_required": False,
        "purpose": ["Culture", "Relaxation"],
        "ideal_months": ["October", "November", "December", "January", "February", "March"],
        "not_ideal_months": ["May", "June", "July", "August"],
        "month_reasons": {
            "October": "Cool season starts, pleasant weather",
            "November": "Festivals and Ganga Mahotsav",
            "December": "Cool and calm, spiritual atmosphere",
            "January": "Cold mornings, perfect for ghats",
            "February": "Comfortable climate, less crowded",
            "March": "Mild weather",
            "May": "Hot and humid",
            "June": "Scorching heat",
            "July": "Monsoon showers",
            "August": "Heavy rain and humidity"
        },
        "places_to_visit": ["Ganga Ghats", "Kashi Vishwanath Temple", "Sarnath", "Ramnagar Fort"]
    },
    {
        "name": "Mysore",
        "type": "local",
        "cost_per_person": [7000, 13000],
        "group_type": ["family", "friends"],
        "visa_required": False,
        "purpose": ["Culture", "Relaxation"],
        "ideal_months": ["October", "November", "December", "January", "February"],
        "not_ideal_months": ["June", "July", "August"],
        "month_reasons": {
            "October": "Dussehra festival, cultural events",
            "November": "Pleasant weather for sightseeing",
            "December": "Cool and tourist-friendly",
            "January": "Comfortable climate",
            "February": "Mild and breezy",
            "June": "Heavy rains",
            "July": "Wet and humid",
            "August": "Monsoon continues"
        },
        "places_to_visit": ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens", "St. Philomena’s Church"]
    },
    {
        "name": "Paris",
        "type": "foreign",
        "cost_per_person": [80000, 120000],
        "group_type": ["family", "friends", "solo"],
        "visa_required": True,
        "purpose": ["Culture", "Luxury", "Relaxation"],
        "ideal_months": ["April", "May", "June", "September", "October"],
        "not_ideal_months": ["December", "January", "February"],
        "month_reasons": {
            "April": "Spring blossoms, fewer tourists",
            "May": "Warm and pleasant",
            "June": "Perfect for sightseeing",
            "September": "Autumn charm, mild weather",
            "October": "Cultural events and cool weather",
            "December": "Cold, holiday rush",
            "January": "Very cold, fewer activities",
            "February": "Chilly and wet"
        },
        "places_to_visit": ["Eiffel Tower", "Louvre Museum", "Notre Dame", "Seine River Cruise"]
    },
    {
        "name": "New York",
        "type": "foreign",
        "cost_per_person": [100000, 150000],
        "group_type": ["family", "friends"],
        "visa_required": True,
        "purpose": ["Culture", "Luxury", "Relaxation"],
        "ideal_months": ["April", "May", "June", "September", "October"],
        "not_ideal_months": ["January", "February", "December"],
        "month_reasons": {
            "April": "Spring starts, ideal weather",
            "May": "Pleasant and lively",
            "June": "Summer fun and events",
            "September": "Fall season, great for Central Park",
            "October": "Cool and festive",
            "December": "Crowded holiday season, cold",
            "January": "Freezing, snowstorms",
            "February": "Cold and harsh"
        },
        "places_to_visit": ["Statue of Liberty", "Central Park", "Times Square", "Empire State Building"]
    },
    {
        "name": "Tokyo",
        "type": "foreign",
        "cost_per_person": [90000, 130000],
        "group_type": ["family", "friends", "solo"],
        "visa_required": True,
        "purpose": ["Culture", "Luxury", "Adventure"],
        "ideal_months": ["March", "April", "May", "October", "November"],
        "not_ideal_months": ["July", "August"],
        "month_reasons": {
            "March": "Cherry blossoms begin",
            "April": "Peak cherry blossom season",
            "May": "Pleasant climate, less crowded",
            "October": "Mild and autumn festivals",
            "November": "Cool weather and autumn leaves",
            "July": "Hot and humid",
            "August": "Very hot, typhoon season"
        },
        "places_to_visit": ["Tokyo Tower", "Shibuya Crossing", "Sensoji Temple", "Disneyland Tokyo"]
    },
    {
        "name": "Hong Kong",
        "type": "foreign",
        "cost_per_person": [60000, 90000],
        "group_type": ["family", "friends"],
        "visa_required": True,
        "purpose": ["Luxury", "Culture", "Relaxation"],
        "ideal_months": ["October", "November", "December", "January"],
        "not_ideal_months": ["June", "July", "August", "September"],
        "month_reasons": {
            "October": "Pleasant weather, start of season",
            "November": "Cool and less humid",
            "December": "Festive and lively",
            "January": "Cool and ideal for sightseeing",
            "June": "Very hot and humid",
            "July": "Rainy and typhoon season",
            "August": "Stormy and humid",
            "September": "Monsoon tail, humid"
        },
        "places_to_visit": ["Victoria Peak", "Disneyland", "Ocean Park", "Star Ferry"]
    },
    {
        "name": "Switzerland",
        "type": "foreign",
        "cost_per_person": [120000, 180000],
        "group_type": ["family", "friends", "solo"],
        "visa_required": True,
        "purpose": ["Nature", "Luxury", "Adventure"],
        "ideal_months": ["May", "June", "July", "August", "September"],
        "not_ideal_months": ["December", "January", "February"],
        "month_reasons": {
            "May": "Spring bloom, pleasant weather",
            "June": "Great for hiking and sightseeing",
            "July": "Summer fun, mountain trails open",
            "August": "Warm and scenic",
            "September": "Autumn charm",
            "December": "Very cold, ski-only activities",
            "January": "Freezing and snowy",
            "February": "Harsh winter, limited travel"
        },
        "places_to_visit": ["Zurich", "Lucerne", "Interlaken", "Matterhorn"]
    },
    {
        "name": "Bali",
        "type": "foreign",
        "cost_per_person": [70000, 110000],
        "group_type": ["family", "friends", "solo"],
        "visa_required": True,
        "purpose": ["Nature", "Adventure", "Relaxation"],
        "ideal_months": ["April", "May", "June", "July", "September"],
        "not_ideal_months": ["December", "January", "February"],
        "month_reasons": {
            "April": "Dry season starts, warm and sunny",
            "May": "Pleasant weather, fewer tourists",
            "June": "Perfect for beaches and temples",
            "July": "Festival season, lively atmosphere",
            "September": "Sunny and less crowded",
            "December": "Rainy and humid",
            "January": "Heavy rainfall, storms",
            "February": "Wet and less travel-friendly"
        },
        "places_to_visit": ["Ubud", "Tanah Lot", "Seminyak", "Mount Batur"]
    },
    {
        "name": "Dubai",
        "type": "foreign",
        "cost_per_person": [60000, 100000],
        "group_type": ["family", "friends"],
        "visa_required": True,
        "purpose": ["Luxury", "Adventure", "Relaxation"],
        "ideal_months": ["November", "December", "January", "February", "March"],
        "not_ideal_months": ["June", "July", "August", "September"],
        "month_reasons": {
            "November": "Cooler evenings, shopping festivals",
            "December": "Festive lights, pleasant days",
            "January": "Perfect for outdoor activities",
            "February": "Mild and breezy",
            "March": "Spring vibes, comfortable climate",
            "June": "Extremely hot, avoid outdoors",
            "July": "Scorching heat",
            "August": "Very humid",
            "September": "Hot and humid"
        },
        "places_to_visit": ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari"]
    }
]
